# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/service/courier_gateway.proto

require 'google/protobuf'

require 'courier/translator/service_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Courier
end
