# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
require 'twirp'
require_relative 'courier_gateway_pb.rb'

module Courier
  class ApiService < Twirp::Service
    package 'courier'
    service 'Api'
    rpc :Translate, TranslateRequest, TranslatedTweet, :ruby_method => :translate
  end

  class ApiClient < Twirp::Client
    client_for ApiService
  end
end
