# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/service/courier_gateway.proto

require 'google/protobuf'

require 'courier/feeds/service_pb'
require 'courier/posts/service_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "courier.UserInfoRequest" do
  end
  add_message "courier.PostsRequest" do
  end
  add_message "courier.UpdateTweetOptionsRequest" do
    optional :id, :int64, 1
    optional :body, :string, 2
    optional :should_post, :bool, 3
  end
  add_message "courier.FeedsRequest" do
  end
  add_message "courier.UserInfo" do
    optional :username, :string, 1
    optional :name, :string, 2
  end
end

module Courier
  UserInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.UserInfoRequest").msgclass
  PostsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.PostsRequest").msgclass
  UpdateTweetOptionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.UpdateTweetOptionsRequest").msgclass
  FeedsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.FeedsRequest").msgclass
  UserInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.UserInfo").msgclass
end
