# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/service/courier_gateway.proto

require 'google/protobuf'

require 'courier/translator/service_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "courier.UserInfoRequest" do
  end
  add_message "courier.UserInfo" do
    optional :username, :string, 1
    optional :name, :string, 2
  end
end

module Courier
  UserInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.UserInfoRequest").msgclass
  UserInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.UserInfo").msgclass
end
