# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
require 'twirp'
require_relative 'feeds_pb.rb'

class FeedsService < Twirp::Service
  service 'Feeds'
  rpc :GetFeeds, GetFeedsRequest, GetFeedsResponse, :ruby_method => :get_feeds
end

class FeedsClient < Twirp::Client
  client_for FeedsService
end
