# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
require 'twirp'
require_relative 'tweets_pb.rb'

class TweetsService < Twirp::Service
  service 'Tweets'
  rpc :GetTweets, GetTweetsRequest, GetTweetsResponse, :ruby_method => :get_tweets
end

class TweetsClient < Twirp::Client
  client_for TweetsService
end
