# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
require 'twirp'
require_relative 'users_pb.rb'

class UsersService < Twirp::Service
  service 'Users'
  rpc :CancelSubscription, CancelSubscriptionRequest, CancelSubscriptionResponse, :ruby_method => :cancel_subscription
  rpc :ReactivateSubscription, ReactivateSubscriptionRequest, ReactivateSubscriptionResponse, :ruby_method => :reactivate_subscription
end

class UsersClient < Twirp::Client
  client_for UsersService
end
